### ISSUE TITLE
[NEW FEATURE] Use external catalogue to replace tile detection

### ISSUE THREAD

**Issue by martinkilbinger** [CosmoStat/shapepipe#648] opened 2023-09-07 06:47 UTC
For the next run we should use the UNIONS tile catalogue created by Stephen Gwyn, instead of performing our own object detection on the tiles. This helps in the comparison with LensFit, and will make it easier to use multi-band data and phot-z's, which are based on the same catalogue.

**Comment by sfarrens** [comment] 2023-11-08 09:28
Duplicate of #632

**Closed as completed by sfarrens** 2023-11-08 09:28 UTC
Labels: enhancement
